import pandas as pd

# Load the CSV generated by eval_methods.py
df = pd.read_csv("results/interp_nf_all_fin/interp_metrics.csv")

# Extract the relevant columns (ITD MAE and ILD MAE) for each method
methods = ["NN", "RBF", "SH", "NEURAL_FIELD", "NEURAL_FIELD_SMOOTH"]
result_columns = ["method", "sparsity_deg", "itd_MAE_ms", "ild_MAE_db"]

# Group by method and sparsity, calculate the mean ITD MAE and ILD MAE
summary = df[df["method"].isin(methods)][result_columns].groupby(["method", "sparsity_deg"]).mean().reset_index()

# Format the output as a LaTeX table
latex_table = summary.pivot(index="method", columns="sparsity_deg", values=["itd_MAE_ms", "ild_MAE_db"])

# Generate LaTeX code for the table
latex_code = latex_table.to_latex(float_format="%.3f", caption="Comparison of ITD and ILD MAE for Different Interpolation Methods", label="tab:itd_ild_comparison")

# Print the LaTeX code
print(latex_code)
